### ISSUE TITLE
"Real robot demo" points to DFKI-NI internal documents

### ISSUE THREAD

**Issue by brean** [DFKI-NI/mobipick_labs#21]
Please publish the [instructions on the wiki](https://git.ni.dfki.de/mobipick/documentation/-/wikis/starting-up-the-robot)

**Comment by mintar** [comment]
Not sure what we should do here:

1. move the instructions to a file in the `mobipick` repo, or:
2. remove the link from the README here.

The instructions are really only useful if you have a real Mobipick robot, and in that case you also have access to the internal documentation. Anyway, either one of those should be done. We need to improve the README anyway (see #13).

**Comment by alexander-sung** [comment]
After discussing options, we decided to keep the instructions internal, according to the reasoning Martin wrote. I tried to clarify the README accordingly, explicitly pointing to internal pages in the two cases: DFKI internal event, and using a real Mobipick robot.
