### ISSUE TITLE
Install up-esb via pip

### ISSUE THREAD

**Issue by jarkenau** [DFKI-NI/mobipick_labs#36]
In https://github.com/aiplan4eu/embedded-systems-bridge/pull/28 I'm currently working on getting the `up-esb` installable via pip. I would also propose to update this repo to this installation method. This way we don't have to clone the full repo and can improve the stability of this demo by specifying a version for the `up-esb` package.

**Comment by mintar** [comment]
That would be great! The only reason we didn't do this yet was because the up-esb did not have a stable pip-installable version yet. Pull request welcome! :)
