### ISSUE TITLE
Missing files for cic_tables scenario

### ISSUE THREAD

**Issue by AmosSmith3** [DFKI-NI/mobipick_labs#39]
When running demo_sim.launch with world and world_config arguments respectively set to pbr_cic and cic_tables (as detailed in the argument documentation), an error (no such file or directory) occurs as the tables_demo_bringup/launch/includes/navigation/cic_tables.launch file does not exist.

I created a launch file based on others in the /includes/navigation directory, but something still does not seem correct - the number of tables (4 tables) in the planning scene does not match the resulting gazebo world (2 tables). Perhaps the configurations for this scenario need to be refactored?

**Comment by mintar** [comment]
I fixed it in 0b35e1f.

Also requires https://github.com/DFKI-NI/mobipick/commit/f451ca7b.

Test like this:

    roslaunch tables_demo_bringup demo_sim.launch world:=pbr_cic world_config:=cic_tables robot_x:=20.40 robot_y:=15.20

You are right, the Gazebo world currently only has 2 of the 4 tables, so perhaps we should add the two missing ones from the map.
