### ISSUE TITLE
Resolve pid error on start-up

### ISSUE THREAD

**Issue by alexander-sung** [DFKI-NI/mobipick_labs#4]
On start-up `roslaunch tables_demo_bringup demo_sim.launch`, these errors appear:

```
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/left_wheel_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/right_wheel_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_shoulder_pan_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_shoulder_lift_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_elbow_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_wrist_1_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_wrist_2_joint [/gazebo]
No p gain specified for pid.  Namespace: /mobipick/gazebo_ros_control/pid_gains/mobipick/ur5_wrist_3_joint [/gazebo]
```

**Comment by alexander-sung** [comment]
I think this is the unlucky error we discussed before. It's still unpleasant to have it undocumented.

**Comment by mintar** [comment]
Yes, this should be documented. We can't make it go away because we didn't specify pid gains on purpose.

**Comment by alexander-sung** [comment]
Shouldn't we just leave this issue open? At least, it would then be visible for anyone who intends to create a similar issue. Or where would you prefer the "documentation"? On the wiki page? Even then, this issue does not seem to be resolved as of now.

**Comment by mintar** [comment]
I added the documentation in the commit that closed this issue (just above your comment), so we can close this issue as there remains nothing to be done. Clever people will still find this issue, even when it's closed.

**Comment by alexander-sung** [comment]
Ok nice. I didn't think of the mobipick repository itself 😅, which already had a "Known Issues" section.
