### ISSUE TITLE
planning no longer perceives objects on real robot

### ISSUE THREAD

**Issue by mintar** [DFKI-NI/mobipick_labs#45]
**Bug description:** On the real mobipick, the planning no longer recognizes any objects with the new code from #42.

When running with the most recent code, the robot just moves from table to table, observes each table, but always thinks it's empty:

```
[INFO] [1709215868.328566]: Newly perceived items: dict_keys([]) (/robot_api_89635)
The believed item locations are:
- multimeter_1: anywhere
- klt_1: anywhere
- klt_2: anywhere
- klt_3: anywhere
```

**Expected behavior:** When running with the old code (before #42 was merged), planning is aware of the objects on the table:

```
[INFO] [1709215907.748825]: Newly perceived items: dict_keys([<Item.box: 'klt_1'>]) (/robot_api_93078)
The believed item locations are:
- box: table_2
- multimeter: anywhere
- Found another item, search ABORTED.
The believed item locations are:
- box: table_2
- multimeter: anywhere
```

**Additional information:** I've bisected the git history, and this is the result:

d3041580d97f5566b6b41fe7ee22cfe35f725ac3 last known good commit
fe0bb681e974c223a9dcf1cc9c2857ac5b1af17c first bad commit? (commit is broken, cannot test)
3ebce0c153a2eafa2a759f24270af02a88304761 first bad commit? (commit is broken, cannot test)
8ce1b86f1c969286e0328206427fc59862d5e692 first bad commit? (commit is broken, cannot test)
b0aea5e7dc06748fba67d000d8a2b1aa1c353857 first bad commit? (commit is broken, cannot test)
9a16fe9a1f711f76fb4d0de5a7611030b41d26a8 first bad commit? (first known bad commit)

The broken commits all show the following error, so it cannot be determined whether they are the bad commit or not.

```
Traceback (most recent call last):
  File "/home/robot/ros/devel/lib/tables_demo_planning/tables_demo_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/robot/ros/src/mobipick_labs/tables_demo_planning/nodes/tables_demo_node.py", line 44, in <module>
    from tables_demo_planning.mobipick_components import Location
ModuleNotFoundError: No module named 'tables_demo_planning.mobipick_components'
```

**How to reproduce:** These are the commands that I ran (on the real robot) to produce this behavior:

```text
roslaunch mobipick_bringup mobipick_bringup_both.launch
roslaunch pbr_dope dope.launch
roslaunch tables_demo_bringup bringup.launch world_config:=cic_tables
rosrun tables_demo_planning tables_demo_node.py
```

**Comment by mintar** [comment]
@alexander-sung @sebastianstock @marcvinci : Could you have a look at this?

**Comment by mintar** [comment]
I've added a section "How to reproduce" to the bug description.

**Comment by alexander-sung** [comment]
Since we tested it both on planning alone and in Gazebo - can we be sure that the real robot indeed perceives the objects?

Additionally, any chance to debug what the symbolic fact generation got vs. what it provides, @marcvinci?

**Comment by marcvinci** [comment]
Currently I am also not sure what causes this problem. The biggest change was to switch to the mobipick_api, so it might be related to that. I will debug it on the real robot on Monday.

@alexander-sung For debugging the symbolic fact generation, you can use the launch file inside the symbolic fact generation repository. Then all current facts are published on the /fact_publisher/facts topic, so you can see what is currently there. For what is provided to the fact generation, you have to check the sources, like pose_selector for objects, joint states for arm poses etc.

**Comment by mintar** [comment]
> Since we tested it both on planning alone and in Gazebo - can we be sure that the real robot indeed perceives the objects?

Yes, because everything works with commit d3041580d97f5566b6b41fe7ee22cfe35f725ac3, but breaks with all commits after that.

**Comment by alexander-sung** [comment]
I understood your bisect method to narrow down the problem, which is helpful indeed. Between the new commits, perception changed to the `mobipick_api`, however, as Marc indicated, so it's still unclear which part is causing the planner's perception list to be empty.

Any ideas, considering it still works in simulation?

This is the old, working code: https://github.com/DFKI-NI/mobipick_labs/blob/d3041580d97f5566b6b41fe7ee22cfe35f725ac3/tables_demo_planning/src/tables_demo_planning/tables_demo_api.py#L207
Ths is the new code which fails to perceive: https://github.com/DFKI-NI/mobipick_labs/blob/noetic/tables_demo_planning/src/tables_demo_planning/tables_demo_api.py#L338
The newly introduced perception is here: https://git.ni.dfki.de/mobipick/mobipick_api/-/blob/noetic/mobipick_api/perception.py#L50

@marcvinci, `self.pose_selector_activate(True)`, moved to `mobipick_api`. The wait there is only 1 second, however, compared to previous 5 seconds, which could be just the difference between reality and simulation.

**Comment by mintar** [comment]
> The wait there is only 1 second, however, compared to previous 5 seconds, which could be just the difference between reality and simulation.

Good catch, this really could be it! I've said for a long time that we should replace this sleep with proper time stamp handling and `wait_for_message` calls. That would have avoided this bug as well (if that's really what's causing this bug)!

**Comment by marcvinci** [comment]
Indeed a good catch @alexander-sung, the sleep was the problem. Increasing it by just one second already fixes it, but I increased it to 3 seconds to be safe. Afterwards I was able to run the complete tables demo on the robot.

**Comment by mintar** [comment]
The robot still had the version with a 2 second sleep initially, which was too short, so the original problem happened again. After updating it to the current version with a 3 second sleep, everything worked while we ran the demo all day, so this issue is solved!
