### ISSUE TITLE
Different UP versions in ESB and install deps script

### ISSUE THREAD

**Issue by oscar-lima** [DFKI-NI/mobipick_labs#48]
[install deps script line 19](https://github.com/DFKI-NI/mobipick_labs/blob/noetic/install-deps.sh#L19) installs ESB version 0.1.0 which installs unified-planning version 1.0.0, however [install deps script line 21](https://github.com/DFKI-NI/mobipick_labs/blob/noetic/install-deps.sh#L21) installs unified-planning version 1.1.0, which results in the following error in the terminal:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
up-esb 0.1.0 requires unified-planning==1.0.0, but you have unified-planning 1.1.0 which is incompatible.
```

Which UP version do we want to have?

**Comment by alexander-sung** [comment]
Probably @sebastianstock can answer this better.

**Comment by mintar** [comment]
The correct version that you want is 1.1.0, and we get the same error message as you. Everything should work correctly with unified-planning 1.1.0, so don't be disturbed by the error message.

To fix this (i.e., to make the error message go away), the authors of `up-esb` should relax their requirements a little (e.g., require `unified-planning>=1.0.0`, not `==`). @sebastianstock or somebody else should open an issue with the `up-esb` authors.

**Comment by jarkenau** [comment]
Related PR https://github.com/aiplan4eu/embedded-systems-bridge/pull/45
