### ISSUE TITLE
Resolve xacro warning on start-up

### ISSUE THREAD

**Issue by alexander-sung** [DFKI-NI/mobipick_labs#7]
On start-up `roslaunch tables_demo_bringup demo_sim.launch`, this warning appears multiple times:

```
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
```

This seems to be caused by the third party module `fmauch_universal_robot` in `ur_description/urdf/inc/ur_common.xacro`.

**Comment by mintar** [comment]
PR opened: https://github.com/fmauch/universal_robot/pull/31

**Comment by mintar** [comment]
Fixed! Simply update, remove `fmauch_universal_robot` from your source workspace and run `rosdep` again to install the binary dependency.

**Comment by alexander-sung** [comment]
Nice, many thanks.
